name: Periodic Health Check

on:
  schedule:
    - cron: '*/5 * * * *' # runs every 5 minutes
  workflow_dispatch: # allows manual trigger

jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:

      - name: Check app health
        run: |
          status=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.DEPLOYED_APP_URL }})
          if [ "$status" -ne 200 ]; then
            echo "App is down! Status code: $status"
            exit 1
          else
            echo "App is healthy! Status code: $status"
          fi
      
      - name: Notify Discord if app is down
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "❌ Health check failed! The application may be down."
          
      - name: Notify Discord if app is healthy
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "✅ Health check passed. Application is running smoothly."
