name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
          
  date_job:
    runs-on: ubuntu-latest
    steps:
     - name: Know the Date
       run: |
         date

  directory_content_job:
    runs-on: ubuntu-latest
    steps:
     - name: Know thy Directory
       run: |
         ls -l
    
   
