name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
      
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies 
        run: npm ci

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      # 🚀 Deploy to Railway only on push to main
      - name: Install Railway CLI
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo "Using Railway CLI version:"
          railway --version
          echo "Deploying..."
          railway up --detach
